FROM tomcat:8.5.15

MAINTAINER "Inna Shpota <shpota_inna@ukr.net>"

RUN rm -rf /usr/local/tomcat/webapps/

ADD docker/postgresql-9.4.1212.jar /usr/local/tomcat/lib/
ADD target/blog.war /usr/local/tomcat/webapps/ROOT.war